# Generated by Django 5.2.17 on 2026-10-06 13:38

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthThrottleBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('window_start', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AccountActionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('confirm', 'Confirmar e-mail'), ('reset', 'Redefinir senha')], max_length=10)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('email_snapshot', models.EmailField(max_length=254)),
                ('auth_snapshot', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_token', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Em envio'), ('sent', 'Enviado'), ('failed', 'Falha'), ('cancelled', 'Cancelado')], default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='accounts.accountactiontoken')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='instituição')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='país')),
                ('preferred_language', models.CharField(choices=[('pt-br', 'Português'), ('en', 'English'), ('es', 'Español')], default='pt-br', max_length=5, verbose_name='idioma preferido')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='accountactiontoken',
            index=models.Index(fields=['expires_at'], name='accounts_ac_expires_35243a_idx'),
        ),
        migrations.AddConstraint(
            model_name='accountactiontoken',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('used_at__isnull', True)), fields=('user', 'purpose'), name='accounts_one_active_action_token'),
        ),
        migrations.AddIndex(
            model_name='accountemail',
            index=models.Index(fields=['status', 'available_at'], name='accounts_ac_status_5ee75f_idx'),
        ),
    ]
