# Generated by Django 5.2.17 on 2026-10-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auththrottlebucket_accountactiontoken_accountemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountemail',
            name='language',
            field=models.CharField(choices=[('pt-br', 'Português'), ('en', 'English'), ('es', 'Español')], default='pt-br', max_length=5),
        ),
    ]
