# Generated by Django 5.2.17 on 2026-10-06 16:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(max_length=64)),
                ('reason', models.CharField(blank=True, max_length=1000)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ('-created_at',),
                'default_permissions': ('view',),
            },
        ),
    ]
