# Generated by Django 5.2.17 on 2026-10-06 16:59

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.contrib.postgres.operations import BtreeGistExtension
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('starts_on', models.DateField(verbose_name='data inicial')),
                ('ends_on', models.DateField(verbose_name='data final')),
                ('timezone_name', models.CharField(default='America/Belem', max_length=64, verbose_name='fuso horário')),
                ('registration_enabled', models.BooleanField(default=False, verbose_name='inscrições habilitadas')),
                ('registration_opens_at', models.DateTimeField(blank=True, null=True, verbose_name='abertura das inscrições')),
                ('registration_closes_at', models.DateTimeField(blank=True, null=True, verbose_name='encerramento das inscrições')),
                ('registration_currency', models.CharField(choices=[('BRL', 'Real (BRL)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (EUR)')], default='BRL', max_length=3, verbose_name='moeda das inscrições')),
                ('jems_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https'])], verbose_name='URL do JEMS')),
            ],
            options={
                'verbose_name': 'evento',
                'ordering': ('starts_on', 'code'),
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='event_dates_valid'), models.CheckConstraint(condition=models.Q(models.Q(('registration_closes_at__isnull', True), ('registration_enabled', False), ('registration_opens_at__isnull', True)), models.Q(('registration_closes_at__gt', models.F('registration_opens_at')), ('registration_closes_at__isnull', False), ('registration_opens_at__isnull', False)), _connector='OR'), name='event_registration_window_valid'), models.CheckConstraint(condition=models.Q(('registration_currency__in', ['BRL', 'USD', 'EUR'])), name='event_currency_valid')],
            },
        ),
        migrations.CreateModel(
            name='RegistrationCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(verbose_name='código')),
                ('name_pt', models.CharField(max_length=255, verbose_name='nome em português')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='nome em inglês')),
                ('name_es', models.CharField(blank=True, max_length=255, verbose_name='nome em espanhol')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
                ('requires_review', models.BooleanField(default=False, verbose_name='exige revisão da comissão')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='registrations.event')),
            ],
            options={
                'verbose_name': 'categoria de inscrição',
                'verbose_name_plural': 'categorias de inscrição',
                'ordering': ('name_pt',),
            },
        ),
        migrations.CreateModel(
            name='RegistrationPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='valor')),
                ('currency', models.CharField(choices=[('BRL', 'Real (BRL)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (EUR)')], default='BRL', max_length=3, verbose_name='moeda')),
                ('valid_from', models.DateTimeField(verbose_name='válido desde')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='válido até (exclusivo)')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='registrations.registrationcategory')),
            ],
            options={
                'verbose_name': 'preço de inscrição',
                'verbose_name_plural': 'preços de inscrição',
                'ordering': ('category__name_pt', 'valid_from'),
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('BRL', 'Real (BRL)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (EUR)')], max_length=3)),
                ('category_name', models.CharField(max_length=255)),
                ('review_required', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Aguardando requisitos'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='pending', max_length=16)),
                ('category_review', models.CharField(choices=[('not_required', 'Não necessária'), ('pending', 'Aguardando revisão'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='not_required', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=1000)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_registrations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='registrations.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='registrations.registrationcategory')),
                ('source_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='registrations.registrationprice')),
            ],
            options={
                'verbose_name': 'inscrição',
                'verbose_name_plural': 'inscrições',
                'ordering': ('-created_at',),
                'permissions': [('review_registration', 'Pode revisar categorias de inscrições'), ('cancel_registration', 'Pode cancelar inscrições com motivo'), ('export_registration', 'Pode exportar dados pessoais de inscrições'), ('view_registration_indicators', 'Pode consultar indicadores de inscrições')],
                'default_permissions': ('view',),
            },
        ),
        migrations.AddConstraint(
            model_name='registrationcategory',
            constraint=models.UniqueConstraint(fields=('event', 'code'), name='category_event_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='registrationprice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='price_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='registrationprice',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ['BRL', 'USD', 'EUR'])), name='price_currency_valid'),
        ),
        migrations.AddConstraint(
            model_name='registrationprice',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='price_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='registrationprice',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('active', True)), expressions=[('category', '='), ('currency', '='), (models.Func(models.F('valid_from'), models.F('valid_until'), models.Value('[)'), function='TSTZRANGE', output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField()), '&&')], name='price_no_active_overlap'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='registration_user_event_unique'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='registration_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ['BRL', 'USD', 'EUR'])), name='registration_currency_valid'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'cancelled'])), name='registration_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.CheckConstraint(condition=models.Q(('category_review__in', ['not_required', 'pending', 'approved', 'rejected'])), name='registration_review_valid'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category_review', 'not_required'), ('review_required', False)), models.Q(('review_required', True), models.Q(('category_review', 'not_required'), _negated=True)), _connector='OR'), name='registration_review_requirement_valid'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('status', 'cancelled'), models.Q(('cancellation_reason', ''), _negated=True)), models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True)), _connector='OR'), name='registration_cancellation_valid'),
        ),
    ]
