# Generated by Django 5.2.17 on 2026-10-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_protect_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='category_name_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='category_name_es',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunSQL(
            sql="""
CREATE OR REPLACE FUNCTION chags_guard_registration() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF ROW(NEW.user_id, NEW.event_id, NEW.category_id, NEW.source_price_id,
               NEW.amount, NEW.currency, NEW.category_name, NEW.category_name_en, NEW.category_name_es, NEW.review_required, NEW.created_at)
           IS DISTINCT FROM ROW(OLD.user_id, OLD.event_id, OLD.category_id, OLD.source_price_id,
               OLD.amount, OLD.currency, OLD.category_name, OLD.category_name_en, OLD.category_name_es, OLD.review_required, OLD.created_at) THEN
            RAISE EXCEPTION 'Registration owner and price snapshot are immutable' USING ERRCODE = '23514';
        END IF;
    ELSE
        IF NEW.status <> 'pending' OR NOT EXISTS (
            SELECT 1 FROM registrations_registrationprice p
            JOIN registrations_registrationcategory c ON c.id = p.category_id
            WHERE p.id = NEW.source_price_id AND c.id = NEW.category_id
              AND c.event_id = NEW.event_id AND p.amount = NEW.amount
              AND p.currency = NEW.currency AND c.name_pt = NEW.category_name
              AND c.name_en = NEW.category_name_en AND c.name_es = NEW.category_name_es
              AND c.requires_review = NEW.review_required
              AND NEW.category_review = CASE WHEN c.requires_review THEN 'pending' ELSE 'not_required' END
        ) THEN
            RAISE EXCEPTION 'Registration must start pending with a matching price and category'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;
""",
            reverse_sql="CREATE OR REPLACE FUNCTION chags_guard_registration() RETURNS trigger LANGUAGE plpgsql AS $$\nBEGIN\n    IF TG_OP = 'UPDATE' THEN\n        IF ROW(NEW.user_id, NEW.event_id, NEW.category_id, NEW.source_price_id,\n               NEW.amount, NEW.currency, NEW.category_name, NEW.review_required, NEW.created_at)\n           IS DISTINCT FROM ROW(OLD.user_id, OLD.event_id, OLD.category_id, OLD.source_price_id,\n               OLD.amount, OLD.currency, OLD.category_name, OLD.review_required, OLD.created_at) THEN\n            RAISE EXCEPTION 'Registration owner and price snapshot are immutable' USING ERRCODE = '23514';\n        END IF;\n    ELSE\n        IF NEW.status <> 'pending' OR NOT EXISTS (\n            SELECT 1 FROM registrations_registrationprice p\n            JOIN registrations_registrationcategory c ON c.id = p.category_id\n            WHERE p.id = NEW.source_price_id AND c.id = NEW.category_id\n              AND c.event_id = NEW.event_id AND p.amount = NEW.amount\n              AND p.currency = NEW.currency AND c.name_pt = NEW.category_name\n              AND c.requires_review = NEW.review_required\n              AND NEW.category_review = CASE WHEN c.requires_review THEN 'pending' ELSE 'not_required' END\n        ) THEN\n            RAISE EXCEPTION 'Registration must start pending with a matching price and category'\n                USING ERRCODE = '23514';\n        END IF;\n    END IF;\n    RETURN NEW;\nEND;\n$$;",
        ),
    ]
